version: '3.9'
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - honeypot_net

  proxy-logger:
    build:
      context: ./proxy_logger
    container_name: proxy-logger
    ports:
      - '1884:1884' # External port for attackers
    depends_on:
      - mqtt-broker
    networks:
      - honeypot_net

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: collector
    depends_on:
      - mqtt-broker
    ports:
      - '8000:8000' # API for frontend
    networks:
      - honeypot_net
    volumes:
      - ./collector/mqtt_honeypot_collector.py:/app/mqtt_honeypot_collector.py

  frontend:
    build:
      context: ./frontend
    container_name: honeypot-frontend
    ports:
      - '5173:5173'
    depends_on:
      - collector
    networks:
      - honeypot_net
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - '1880:1880'
    networks:
      - honeypot_net

networks:
  honeypot_net:
    driver: bridge
